spring.application.name=examples


# Enable the H2 console
spring.h2.console.enabled=true
# (Optional) Set a custom path for the console. The default is /h2-console
spring.h2.console.path=/h2-console
# Configure the database connection so it doesn't auto-generate a random URL every restart
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE


logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=TRACE
logging.level.org.springframework.transaction.interceptor=TRACE